# Generated by Django 2.2.16 on 2020-09-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salesman',
        ),
    ]
