# Generated by Django 2.2.16 on 2020-09-15 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_moveshoptowarehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveShopToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shop')),
                ('warehouse', models.ForeignKey(on_delete=None, to='core.Warehouse')),
            ],
        ),
    ]
