# Generated by Django 2.2.16 on 2020-09-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=None, to='core.Shop'),
        ),
    ]
