# Generated by Django 2.2.16 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_moveshoptowarehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveshoptowarehouse',
            name='move',
            field=models.CharField(choices=[('S2W', 'Shop to Warehouse'), ('W2S', 'Warehouse to Shop')], max_length=3, null=True),
        ),
    ]
