# Generated by Django 2.2.16 on 2020-09-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_moveshoptowarehouse_move'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoveShopToWarehouse',
            new_name='MoveProduct',
        ),
    ]
