# Generated by Django 2.2.16 on 2020-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_warehouseproducts_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrasnscation',
            name='delivery_warehouse',
            field=models.ForeignKey(null=True, on_delete=None, to='core.Warehouse'),
        ),
        migrations.AlterField(
            model_name='vendortrasnscation',
            name='vendor',
            field=models.ForeignKey(on_delete=None, to='core.Vendor'),
        ),
    ]
