# Generated by Django 2.2.16 on 2020-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200909_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
