# Generated by Django 2.2.16 on 2020-09-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200915_0820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproducts',
            unique_together={('warehouse', 'product')},
        ),
    ]
