# Generated by Django 2.2.16 on 2020-09-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customerordereditems_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='product_detail',
        ),
    ]
