# Generated by Django 2.2.16 on 2020-09-19 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customerordereditems_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordereditems',
            name='product_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='core.Product'),
        ),
    ]
