# Generated by Django 2.2.16 on 2020-09-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200915_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorordereditems',
            unique_together={('order', 'product', 'delivery_warehouse')},
        ),
    ]
