# Generated by Django 2.2.16 on 2020-09-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200919_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordereditems',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorordereditems',
            name='buying_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='customerordereditems',
            unique_together={('order', 'shop', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorordereditems',
            unique_together={('order', 'shop', 'product', 'delivery_warehouse')},
        ),
    ]
