# Generated by Django 2.2.16 on 2020-10-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200923_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_alert_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
