# Generated by Django 2.2.16 on 2020-09-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customerordereditems_customertrasnscation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertrasnscation',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
