# Generated by Django 2.2.16 on 2020-09-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customertrasnscation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertrasnscation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='product',
        ),
        migrations.AddField(
            model_name='customertrasnscation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=None, to='core.Product'),
        ),
    ]
