# Generated by Django 2.2.16 on 2020-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
