# Generated by Django 2.2.16 on 2020-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200910_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='product',
        ),
        migrations.AddField(
            model_name='customertrasnscation',
            name='product',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
