# Generated by Django 2.2.16 on 2020-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201010_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subject',
            field=models.CharField(default='Empty', max_length=255),
        ),
    ]
