# Generated by Django 2.2.16 on 2020-09-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200910_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customerordereditems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='customerordereditems',
            name='order',
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='order',
            field=models.ManyToManyField(to='core.CustomerTrasnscation'),
        ),
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='product',
        ),
        migrations.AddField(
            model_name='customertrasnscation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
