# Generated by Django 2.2.16 on 2020-10-11 09:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_expense_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrasnscation',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.transaction_image_file_path),
        ),
    ]
