# Generated by Django 2.2.16 on 2020-09-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customerordereditems_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='shop',
        ),
    ]
