# Generated by Django 2.2.16 on 2020-10-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201011_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_buying_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
