# Generated by Django 2.2.16 on 2020-09-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_customerordereditems_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='order',
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CustomerTrasnscation'),
        ),
    ]
