# Generated by Django 2.2.16 on 2020-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200910_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='order',
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='order',
            field=models.ManyToManyField(to='core.CustomerTrasnscation'),
        ),
    ]
