# Generated by Django 2.2.16 on 2020-10-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vendorordereditems_custom_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordereditems',
            name='custom_selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
