# Generated by Django 2.2.16 on 2020-09-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200910_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordereditems',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Shop'),
        ),
    ]
