# Generated by Django 2.2.16 on 2020-09-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_customerordereditems_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='customertrasnscation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
