# Generated by Django 2.2.16 on 2020-09-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200910_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerordereditems',
            name='order',
        ),
        migrations.AddField(
            model_name='customerordereditems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CustomerTrasnscation'),
        ),
    ]
