# Generated by Django 2.2.16 on 2020-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200910_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerordereditems',
            name='bill',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
