# Generated by Django 2.2.16 on 2020-09-11 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_customerordereditems_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTrasnscationBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.PositiveIntegerField(default=0)),
                ('paid', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomerTrasnscation')),
            ],
        ),
    ]
