# Generated by Django 2.2.16 on 2020-09-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customertrasnscationbill_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertrasnscationbill',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CustomerTrasnscation', unique=True),
        ),
    ]
