# Generated by Django 2.2.16 on 2020-09-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200911_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertrasnscationbill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.CustomerTrasnscation'),
        ),
    ]
