# Generated by Django 2.2.16 on 2020-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200912_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortrasnscationbill',
            name='due',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
